version: '3'

services:
  server:
    build: ./demo/
    ports:
      - "5000:5000"
    restart: always
  client:
    build: ./client/
    links:
      - "server"
    depends_on:
      - "server"
    ports:
      - "4200:4200"